title: data wants to be free
description: Some thoughts on software and life in general.
url: https://tommie.github.io/
github_username: tommie
markdown: kramdown
highlighter: pygments
permalink: /a/:year/:month/:title
analytics:
  ga_tracking_id: "%55%41%2D%36%32%33%30%33%33%30%38%2D%31"
defaults:
  - scope:
      path: ""
    values:
      layout: base
  - scope:
      path: ""
      type: posts
    values:
      author: tommie
      layout: post
